### ISSUE TITLE
inheriting javadocs for aliases

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/mrdocs#360]
Consider:
```
/** A value
*/
struct T {};

struct C
{
  using type = T;
};
```

Should `type` automatically reference the Javadoc for `T` because it does not have its own doc? Or should this be an option? Or should we require the user write `@copydoc`:

```
struct C
{
  /// @copydoc T
  using type = T;
};
```

What if there is additional commenting?
```
struct C
{
  /** @copydoc T

      and more
  */
  using type = T;
};
```

**Comment by alandefreitas** [comment]
If we do what doxygen does, `C::type` will have no documentation. This seems correct because `C::type` is semantically different from T in that its documentation usually describes what it means in the context of `C`. However, it's still not unreasonable to assume `@copydoc T` there.

> What if there is additional commenting?

I think this is an independent question because it might happen in other contexts. But the answer is that the additional comments are appended because `@copydoc foo()` is roughly equivalent to doing:

```
  \brief \copybrief foo()
  \details \copydetails foo()
```

https://www.doxygen.nl/manual/commands.html#cmdcopydoc

**Comment by vinniefalco** [comment]
I think in `using type = T` the T should be a hyperlink and we can call it a day.

**Comment by sdkrystian** [comment]
@vinniefalco Sounds good. We already link `T`, so this is complete.
