### ISSUE TITLE
Infinite recursion while detecting SFINAE

### ISSUE THREAD

**Issue by Nerixyz** [cppalliance/mrdocs#665]
I was trying to compile MrDocs and ran into a stack-overflow while building the documentation for MrDocs itself (which is build by default).

The error occurs when trying to detect whether [`fmt::formatter`](https://github.com/fmtlib/fmt/blob/10.2.1/include/fmt/core.h#L1086-L1090) is such a template. One of its specializations is in [`mrdocs/Dom/String.hpp`](https://github.com/cppalliance/mrdocs/blob/bd54dc7c2562ec751e42fb161116468a4838cb6d/include/mrdocs/Dom/String.hpp#L344-L355). In this specialization, the `fmt::formatter` extends its own template. When checking for SFINAE, the base template is checked as well, leading to infinite recursion.

The following change "fixes" the issue, but I don't know if it's correct to just "ignore" that base class.
```diff
diff --git a/src/lib/AST/ASTVisitor.cpp b/src/lib/AST/ASTVisitor.cpp
index 1d48999..893997e 100644
--- a/src/lib/AST/ASTVisitor.cpp
+++ b/src/lib/AST/ASTVisitor.cpp
@@ -1723,6 +1723,8 @@ public:
                             return true;
                         continue;
                     }
+                    if (sfinae_info->Template == TD)
+                        continue;
                     auto sfinae_result = isSFINAETemplate(
                         sfinae_info->Template, Member);
                     if(! sfinae_result)
```

Minimal example:

```cpp
template <typename T> struct Foo {};
template<> struct Foo<char> : public Foo<int> {};
```

This isn't caught in CI, as the docs generation is disabled there.

----

_Aside:_

- The documentation generation from CMake doesn't work right now, because it tries to find a [`local-antora-playbook.yml`](https://github.com/cppalliance/mrdocs/blob/bd54dc7c2562ec751e42fb161116468a4838cb6d/CMakeLists.txt#L439) - this should probably be `antora-playbook.yml`.
- MSVC fails to compile `lib/AST/ASTVisitor.cpp`, because [`CompleteExternalDeclaration`](https://github.com/cppalliance/mrdocs/blob/bd54dc7c2562ec751e42fb161116468a4838cb6d/src/lib/AST/ASTVisitor.cpp#L4681) is overridden with a `DeclaratorDecl*`, but [declared with a `VarDecl*`](https://github.com/llvm/llvm-project/blob/7a28a5b3fee6c78ad59af79a3d03c00db153c49f/clang/include/clang/AST/ASTConsumer.h#L108) in the version referenced on https://mrdocs.com/docs/mrdocs/install.html (7a28a5b3fee6c78ad59af79a3d03c00db153c49f; I suppose that version is outdated)

**Comment by alandefreitas** [comment]
I just reproduced the problem and can confirm it. For reference, I built the MrDocs documentation with:

```bash
mrdocs \
	--config="path\to\mrdocs\docs\mrdocs.yml"
	--output="path\to\mrdocs\build\reference"
	--addons=path/to/mrdocs/share/mrdocs/addons
	--stdlib-includes=path/to/libraries/llvm/include
	--concurrency 1
	--compilation-database=path\to\mrdocs\build\release-msvc\compile_commands.json
```

(omitting the path/to/mrdocs for brevity and privacy)

The stack trace is something like:

- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/Lib/CorpusImpl.cpp#L198
- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/Lib/CorpusImpl.cpp#L155
- `clang::tooling::ClangTool::run`
- ...
- `clang::FrontEndAction::Execute`
- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/AST/ASTVisitor.cpp#L4756
- `clang::ParseAST`
- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/AST/ASTVisitor.cpp#L4623
- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/AST/ASTVisitor.cpp#L426
- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/AST/ASTVisitor.cpp#L3366
- `include/clang/AST/DeclNodes.inc`: `TRANSLATIONUNIT(TranslationUnit, Decl)`
- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/AST/ASTVisitor.cpp#L3395
- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/AST/ASTVisitor.cpp#L3343
- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/AST/ASTVisitor.cpp#L3405
- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/AST/ASTVisitor.cpp#L3366
- `include/clang/AST/DeclNodes.inc`: `NAMESPACE(Namespace, NamedDecl)`
- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/AST/ASTVisitor.cpp#L3395
- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/AST/ASTVisitor.cpp#L3041
- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/AST/ASTVisitor.cpp#L3405
- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/AST/ASTVisitor.cpp#L3366
- `include/clang/AST/DeclNodes.inc`: `NAMESPACE(Namespace, NamedDecl)`
- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/AST/ASTVisitor.cpp#L3395
- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/AST/ASTVisitor.cpp#L3041
- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/AST/ASTVisitor.cpp#L3405
- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/AST/ASTVisitor.cpp#L3366
- `include/clang/AST/DeclNodes.inc`: `CLASSTEMPLATE(ClassTemplate, RedeclarableTemplateDecl)`
- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/AST/ASTVisitor.cpp#L3377
- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/AST/ASTVisitor.cpp#L3366
- `include/clang/AST/DeclNodes.inc`: `CXXRECORD(CXXRecord, RecordDecl)`
- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/AST/ASTVisitor.cpp#L3395
- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/AST/ASTVisitor.cpp#L3201
- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/AST/ASTVisitor.cpp#L3405
- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/AST/ASTVisitor.cpp#L3366
- `include/clang/AST/DeclNodes.inc`: `TYPEALIASTEMPLATE(TypeAliasTemplate, RedeclarableTemplateDecl)`
- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/AST/ASTVisitor.cpp#L3377
- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/AST/ASTVisitor.cpp#L3366
- `include/clang/AST/DeclNodes.inc`: `TYPEALIAS(TypeAlias, TypedefNameDecl)`
- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/AST/ASTVisitor.cpp#L3395
- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/AST/ASTVisitor.cpp#L3333
- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/AST/ASTVisitor.cpp#L2295
- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/AST/ASTVisitor.cpp#L4268
- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/AST/ASTVisitor.cpp#L1870
- Then the infinite loop...
	- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/AST/ASTVisitor.cpp#L1792
	- https://github.com/cppalliance/mrdocs/blob/8537d3dbc71878a3ea6e176b0d25af8d0d51e799/src/lib/AST/ASTVisitor.cpp#L1726
	- ...

@sdkrystian Please have a look at this logic and the proposed solution:

```cpp
+                    if (sfinae_info->Template == TD)
+                        continue;
```

My intuition is the solution is going to be more complex than that.

> The documentation generation from CMake doesn't work right now, because it tries to find a [local-antora-playbook.yml](https://github.com/cppalliance/mrdocs/blob/bd54dc7c2562ec751e42fb161116468a4838cb6d/CMakeLists.txt#L439) - this should probably be antora-playbook.yml.

I opened another issue for this one: #680

> MSVC fails to compile lib/AST/ASTVisitor.cpp, because [CompleteExternalDeclaration](https://github.com/cppalliance/mrdocs/blob/bd54dc7c2562ec751e42fb161116468a4838cb6d/src/lib/AST/ASTVisitor.cpp#L4681) is overridden with a DeclaratorDecl*, but [declared with a VarDecl*](https://github.com/llvm/llvm-project/blob/7a28a5b3fee6c78ad59af79a3d03c00db153c49f/clang/include/clang/AST/ASTConsumer.h#L108) in the version referenced on https://mrdocs.com/docs/mrdocs/install.html (7a28a5b3fee6c78ad59af79a3d03c00db153c49f; I suppose that version is outdated)

Interesting. But yes, this should be done in `develop` because we have no problems in CI.
