### ISSUE TITLE
How do I use `mrdocs` with a header-only library?

### ISSUE THREAD

**Issue by akrzemi1** [cppalliance/mrdocs#673]
My library is a single-header (header-only) library. I do not have a CMake configuration for it. 
Can I still use `mrdocs` to generate a reference for it?

**Comment by vinniefalco** [comment]
Yes. You need to create one or more individual .cpp files which include the headers you want to build the reference for. Then create cmake file which builds it. Alternatively you can create the needed Compile_Commands.JSON file yourself.

**Comment by akrzemi1** [comment]
Are you offering this as a temporary hack, or an ultimate solution?

**Comment by alandefreitas** [comment]
We have a section in the documentation about common project layouts: https://mrdocs.com/docs/mrdocs/develop/usage.html#_mrdocs_invocation. In your case, you are probably interested in https://mrdocs.com/docs/mrdocs/develop/usage.html#_mrdocs_builds, which is the pattern we also use for Boost.URL

For now, you'll need a CMakeLists.txt or a compile_commands.json file. It could be a very simple file with a single TU that includes all headers. For Boost.URL, we have a MrDocs target that consists of all header files in a single TU here: https://github.com/boostorg/url/blob/78ed463014e161c7a980696803a4948a29375c6c/CMakeLists.txt#L155-L161

It may feel weird to have a CMakeLists.txt with a target to include all headers in a directory, especially if you're coming from Doxygen or any other clang-based tool that has the option of doing that for you. It's also weird because the documentation content only comes from the header files. However, for MrDocs, things are a little more complex than Doxygen because the tool only accepts valid C++ code. 

In principle, it's possible to generate the compilation database for the user in straightforward cases (what would be "standalone" mode). However, we have discussed some patterns, and developing a good design is somewhat complex. For instance, https://github.com/standardese/standardese also requires valid code and attempts to do that. Still, their solution is slightly unsatisfactory (it creates a compilation database with all header files) because it can lead to surprises in the output that are hard to understand. In any case, it's something to keep considering, as many, if not most, library projects just need TUs with all headers compiled with the same options for the documentation.

**Comment by akrzemi1** [comment]
If I can make a suggestion, the [URL approach](https://github.com/boostorg/url/blob/78ed463014e161c7a980696803a4948a29375c6c/CMakeLists.txt#L155-L161) is the one that should be recommended. Once you explained to me that the code needs to compile, it becomes clear that `CMakeList.txt` will have to be employed. Creating the `.cpp` file on the fly seems the best way to go, as I do not want to insert a `.cpp` file into my sources that neither tests nor the users will need.

What I would recommend is to put a section in the docs that explains "how to use mrdocs with header-only libraries".

**Comment by vinniefalco** [comment]
> Creating the .cpp file on the fly seems the best way to go

I don't think so. A single .cpp file is not going to perform well. You want to have multiple cpp files to take advantage of parallelism and also to keep memory consumption down. But which headers to include? Well, detail headers may not be needed since they don't have public interfaces. What are the detail headers though? Also, there is no point to including the "include-all" headers such as <boost/urls.hpp>.

It is not really practical to have the build system figure out how to do it. 

> I do not want to insert a .cpp file into my sources that neither tests nor the users will need

That sounds like a personal issue. The cpp files are needed by the documentation system, what makes this less important than tests or users?

**Comment by vinniefalco** [comment]
I see... @alandefreitas this is not good guidance. Forcing the entire AST tree into memory at once is not sustainable. If you want, you can do something like this (apologies if this is not proper cmake)
```
Set( PUBLIC_HEADERS,
  "boost/url/url.hpp",
  "boost/url/url_view.hpp"
   ...)
```

And then you can have a cmake function or something which creates one cpp file for each header in PUBLIC_HEADERS.

**Comment by alandefreitas** [comment]
> A single .cpp file is not going to perform well

That's misleading. 

For Boost.URL, we went from ~8.5 minutes to ~3 seconds by moving from the original target (feeding MrDocs with the usual Boost.URL target users would use) to a Unity Build that discards undocumented content (one target crafted just for MrDocs with a single .cpp file, including all headers). 

And there are two reasons for this:

- Multiple TUs must reinclude and parse all the same headers they transitively include
- The original Boost.URL target users typically use includes all the source content that's much larger than the header content but contains no information for the documentation (it potentially could have information MrDocs would use, but it doesn't and shouldn't).

So "a single .cpp file is not going to perform well" only when compared with an ideal and even more customized Distributed Unity Build that creates N targets for N cores (which we didn't implement for other reasons). Even in this case, nothing close to the perfect linear speedup of N for N cores will ever be achieved because different TUs will extract the same transitive symbols as other TUs.

**Comment by akrzemi1** [comment]
I tried to use the instructions in https://mrdocs.com/docs/mrdocs/develop/usage.html#_mrdocs_builds
and failed.
My [CMakeLists.txt](https://github.com/user-attachments/files/17180875/CMakeLists.txt) file.
Contents of by `mrdocs.yml` file:
```
source-root: ../include
multipage: false
generate: adoc
implementation-detail: 'detail_'
cmake: "-D MY_PROJECT_MRDOCS_BUILD=ON"
compilation-database: ../CMakeLists.txt
output: ./reference
```

I get an error that does not refer to my files, and that I do not understand:
```
Failed to generate compile_commands.json file: CMake executable not found (src/lib/Lib/CMakeExecution.cpp:28)
    Reported at src/tool/GenerateAction.cpp(131)
Generating reference failed: CMake executable not found (src/lib/Lib/CMakeExecution.cpp:28)
    Reported at src/tool/ToolMain.cpp(83)
```

**Comment by alandefreitas** [comment]
> failed

Documentation needs to improve but the error is correct here. As MrDocs doesn't bundle CMake, if the `compilation-database` is a `CMakeLists.txt`, then `cmake` needs to be available in one of the paths in `PATH` or `$CMAKE_ROOT/bin`. We're open to more suggestions about this one.

> I get an error that does not refer to my files, and that I do not understand:

Whenever there's an error, it prints the MrDocs stacktrace. The idea is that users can paste this stack trace when opening an issue. It was quite helpful this time already. We're also open to suggestions. Maybe we can improve this error message or the documentation.

**Comment by akrzemi1** [comment]
Your response helped me move forward. 
I recommend that the error messages should say something similar.
1. Issue a command that command `cmake` is not available.
2. The "stack trace" idea is good. But if the message could just say "copy the following stack trace and paste it into the bug report".

**Comment by akrzemi1** [comment]
And maybe you can help me with this one:
```
Failed to generate compile_commands.json file: CMake execution failed:
CMake Error at CMakeLists.txt:13 (target_include_directories):
  Cannot specify include directories for target "PUBLIC" which is not built
  by this project.


 (src/lib/Lib/CMakeExecution.cpp:468)
    Reported at src/tool/GenerateAction.cpp(131)
Generating reference failed: CMake execution failed:
CMake Error at CMakeLists.txt:13 (target_include_directories):
  Cannot specify include directories for target "PUBLIC" which is not built
  by this project.


 (src/lib/Lib/CMakeExecution.cpp:468)
    Reported at src/tool/ToolMain.cpp(83)
```

**Comment by akrzemi1** [comment]
Now I am getting an itheresting one:

```
Failed to generate compile_commands.json file: CMake execution failed:
CMake Error at CMakeLists.txt:17 (file):
  file failed to open for writing (Permission denied):

    // This file is generated automatically by CMake





 (src/lib/Lib/CMakeExecution.cpp:468)
    Reported at src/tool/GenerateAction.cpp(131)
Generating reference failed: CMake execution failed:
CMake Error at CMakeLists.txt:17 (file):
  file failed to open for writing (Permission denied):

    // This file is generated automatically by CMake





 (src/lib/Lib/CMakeExecution.cpp:468)
    Reported at src/tool/ToolMain.cpp(83)
```

**Comment by alandefreitas** [comment]
> Now I am getting an iteresting one

Yes, that is interesting. It looks like CMake is having some permission issues with the very same build files it generated. We could check the permissions for the temporary directory where MrDocs is asking cmake to put the build files. And then compare that with the user running mrdocs.

I know it uses whatever location the system thinks is best for temporary directories, but the function used to generate these temporary files [is not properly documented](https://llvm.org/docs/doxygen/namespacellvm_1_1sys_1_1fs.html#abf677459f5137cfb49f6d81b27ea54a1).

I have to check what that usually is on Linux. But whatever the temporary directory is, mrdocs appends `mrdocs` to the temporary directory path, so you can probably also find it with:

```
find /tmp /var/tmp ~ -type d -name "mrdocs" 2>/dev/null
```

or

```
find / -type d -name "mrdocs" 2>/dev/null
```

or 

```
locate mrdocs
```

**Comment by akrzemi1** [comment]
Let me just remark that I am using Ubuntu on WSL.

**Comment by alandefreitas** [comment]
Yes. I'm taking this into account. That's probably why we haven't had permission errors before. The function that creates the temp directory should probably be creating this directory somewhere where you already have appropriate permissions.

**Comment by akrzemi1** [comment]
```
/mnt/c/Program Files/MrDocs 0.0.2/include/mrdocs
/mnt/c/Program Files/MrDocs 0.0.2/lib/cmake/mrdocs
/mnt/c/Program Files/MrDocs 0.0.2/share/mrdocs
/mnt/c/Users/pc/Downloads/MrDocs-0.0.2-win64/MrDocs-0.0.2-win64/include/mrdocs
/mnt/c/Users/pc/Downloads/MrDocs-0.0.2-win64/MrDocs-0.0.2-win64/lib/cmake/mrdocs
/mnt/c/Users/pc/Downloads/MrDocs-0.0.2-win64/MrDocs-0.0.2-win64/share/mrdocs
/mnt/c/Users/pc/source/mrdocs
/mnt/c/Users/pc/source/mrdocs/MrDocs-0.0.2-Linux/include/mrdocs
/mnt/c/Users/pc/source/mrdocs/MrDocs-0.0.2-Linux/lib/cmake/mrdocs
/mnt/c/Users/pc/source/mrdocs/MrDocs-0.0.2-Linux/share/mrdocs
```
None of them looks like temp file.

**Comment by alandefreitas** [comment]
What's at line 17 of your CMakeLists.txt?

**Comment by akrzemi1** [comment]
```
    file(WRITE ${OUTPUT_FILE} "// This file is generated automatically by CMake\n\n")
```

Here's the entire content

```
project(markable)
cmake_minimum_required(VERSION 2.6...3.22)
add_library(markable INTERFACE)
target_include_directories(markable INTERFACE include)

enable_testing()

set(CMAKE_CXX_FLAGS "-std=c++0x -Wall -Wextra -DAK_TOOLBOX_NO_UNDERLYING_TYPE")

if (MY_PROJECT_MRDOCS_BUILD)
    # Glob all header files
    set(INCLUDE_DIR "${CMAKE_SOURCE_DIR}/include")
    file(GLOB_RECURSE HEADER_FILES "${INCLUDE_DIR}/*.hpp")

    # Create a temporary source file that includes all header files
    set(TEMP_CPP_FILE "${CMAKE_CURRENT_BINARY_DIR}/all_headers.cpp")
    file(WRITE ${OUTPUT_FILE} "// This file is generated automatically by CMake\n\n")
    foreach(HEADER_FILE ${HEADER_FILES_LIST})
        file(APPEND ${OUTPUT_FILE} "#include \"${HEADER_FILE}\"\n")
    endforeach()

    # Create a custom target for MrDocs
    add_library(my_project_mrdocs_target ${TEMP_CPP_FILE})

    # Set any other target properties here
    target_include_directories(my_project_mrdocs_target PRIVATE ${INCLUDE_DIR})
    target_link_libraries(my_project_mrdocs_target PRIVATE an_external_library)

    # Don't create any other targets
    return()
endif()

add_executable(test_markable test/test_markable.cpp)

add_test(test_markable test_markable)

```

**Comment by alandefreitas** [comment]
Oh... 

Where does `OUTPUT_FILE` come from? Shouldn't it be `TEMP_CPP_FILE`?

You can just

```cmake
message(STATUS "${OUTPUT_FILE}")
message(STATUS "${TMP_CPP_FILE}")
```

to print where the file is and check the permission issues. 

But I'm guessing the problem is just that `OUTPUT_FILE` is an invalid location that's why CMake is giving you that error.

**Comment by akrzemi1** [comment]
You are correct. I do not know cmake and I mechanically copied the solution from 
https://mrdocs.com/docs/mrdocs/develop/usage.html#_mrdocs_builds

And it has a bug.

It should be:
```
    # Create a temporary source file that includes all header files
    set(TEMP_CPP_FILE "${CMAKE_CURRENT_BINARY_DIR}/all_headers.cpp")
    file(WRITE ${TEMP_CPP_FILE} "// This file is generated automatically by CMake\n\n")
    foreach(HEADER_FILE ${HEADER_FILES_LIST})
        file(APPEND ${TEMP_CPP_FILE} "#include \"${HEADER_FILE}\"\n")
    endforeach()
```

But there is still something wrong with it, as mrdocs now renders output with zero definitions.

**Comment by akrzemi1** [comment]
Ok, I got it. The correct thing to put to CMakeLists.txt is:

```
if (MY_PROJECT_MRDOCS_BUILD)
    # Glob all header files
    set(INCLUDE_DIR "${CMAKE_SOURCE_DIR}/include")
    file(GLOB_RECURSE HEADER_FILES "${INCLUDE_DIR}/*.hpp")

    # Create a temporary source file that includes all header files
    set(TEMP_CPP_FILE "${CMAKE_CURRENT_BINARY_DIR}/all_headers.cpp")
    file(WRITE ${TEMP_CPP_FILE} "// This file is generated automatically by CMake\n\n")
    foreach(HEADER_FILE ${HEADER_FILES})
        file(APPEND ${TEMP_CPP_FILE} "#include \"${HEADER_FILE}\"\n")
    endforeach()

    # Create a custom target for MrDocs
    add_library(my_project_mrdocs_target ${TEMP_CPP_FILE})

    # Set any other target properties here
    target_include_directories(my_project_mrdocs_target PRIVATE ${INCLUDE_DIR})
    target_link_libraries(my_project_mrdocs_target PRIVATE an_external_library)

    # Don't create any other targets
    return()
endif()
```

**Comment by alandefreitas** [comment]
Phew... not a bug after all.

**Comment by akrzemi1** [comment]
Well, a bug in docs for Mr Docs.

Ok, so the page you linked, it is not part of the official docs. is it going to be released along with the newest release of Mr Docs?
Is it anytime soon?

Anyway, thans a lot for your help!

**Comment by alandefreitas** [comment]
> Ok, so the page you linked, it is not part of the official docs. is it going to be released along with the newest release of Mr Docs?
Is it anytime soon?

Mm... It's probably still in develop. But yes. It'll all go to master.
